### ISSUE TITLE
Global InlineSVGModule.forRoot configuration does not work in lazy loaded modules

### ISSUE THREAD

**Issue by nathanosdev** [arkon/ng-inline-svg#80] opened 2018-06-06 13:56 UTC
Reproduction:
- https://stackblitz.com/edit/angular-r9cqys
- https://angular-r9cqys.stackblitz.io

When calling `InlineSVGModule.forRoot({ baseUrl: 'https://dev.w3.org/SVG/tools/svgweb/samples/svg-files' })` inside `app.module.ts`, the `baseUrl` is not carried into lazy modules when there is no `inlineSVG` directive used inside non-lazy loaded components.

In the reproduction, navigate to the lazy loaded route and check then network panel. You will see that requests for SVGs are made against `/` instead of the base URL that I provided `https://dev.w3.org/SVG/tools/svgweb/samples/svg-files`.

You can work around the issue by using an `inlineSVG` directive or injecting the `SVGCacheService` somewhere in a non-lazy loaded component. Then you will see that the SVG in the lazy loaded component is actually made against the correct base URL.

Note that the SVG requests in the repro are not working due to CORS issues, but focus on the request URL rather than the actual response.

**Comment by arkon** [comment] 2018-06-06 21:25
I'll need to look into this since I haven't really used Angular since before they introduced lazy loaded modules...

**Comment by nathanosdev** [comment] 2018-06-07 09:09
Don't worry, I'll make a PR with a fix today!

**Comment by philly-vanilly** [comment] 2019-05-11 08:38
This is still not working; please reopen the issue. The only way I can use lazy loaded modules with this lib is with HashLocationStrategy.

**Comment by nathanosdev** [comment] 2019-05-11 16:18
@philly-vanilly are you sure it's the same issue? If you can provide a reproduction I might be able to help, but as far as my original issue is concerned it's working now and has been in production without issues for 8 months.

**Comment by philly-vanilly** [comment] 2019-05-13 10:44
@AnimaMundi ok you can close the issue. I use Angular Material now, so I can't reproduce it anymore. When I had the issue, the problem occurred when using PathLocationStrategy with lazily loaded modules (in separate libs, we are using NX; but this shouldn't matter). The href in the SVG/use was always routing to http://localhost:4200 instead of http://localhost:4200/some/route and only the latter would display icons.

**Closed as completed** 2019-05-13 11:44 UTC
