### ISSUE TITLE
Exception on failed HTTP call

### ISSUE THREAD

**Issue by JohnKis** [arkon/ng-inline-svg#152] opened 2020-10-20 10:31 UTC
When trying to load an SVG url and the request fails for any reason, the following exception will be triggered:

```
TypeError: Cannot read property 'charAt' of null
    at charAt (webpack:///node_modules/ng-inline-svg/__ivy_ngcc__/lib_esmodule/svg-util.js:2:15)
    at call (webpack:///node_modules/rxjs/_esm2015/internal/Subscriber.js:183:15)
    at __tryOrUnsub (webpack:///node_modules/rxjs/_esm2015/internal/Subscriber.js:122:21)
    at next (webpack:///node_modules/rxjs/_esm2015/internal/Subscriber.js:72:25)
    at _next (webpack:///node_modules/rxjs/_esm2015/internal/Subscriber.js:49:17)
    at next (webpack:///node_modules/rxjs/_esm2015/internal/operators/map.js:35:25)
    at _next (webpack:///node_modules/rxjs/_esm2015/internal/Subscriber.js:49:17)
    at next (webpack:///node_modules/rxjs/_esm2015/internal/Subscriber.js:72:25)
    at _next (webpack:///node_modules/rxjs/_esm2015/internal/Subscriber.js:49:17)
    at next (webpack:///node_modules/rxjs/_esm2015/internal/Subject.js:39:24)
```

Upon a brief look it seems to be caused by the finalize operator in [SVGCacheService](https://github.com/arkon/ng-inline-svg/blob/master/src/svg-cache.service.ts#L62) because of which the error callback will never be called in the subscription in the directive.

**Comment by arkon** [comment] 2020-12-06 15:09
Duplicate of #149

**Closed as completed by arkon** 2020-12-06 15:09 UTC
Labels: bug
