### ISSUE TITLE
WARNING eedefineInjectable and eeinject was not found in '@angular/core'

### ISSUE THREAD

**Issue by ikismail** [arkon/ng-inline-svg#135] opened 2020-02-27 06:26 UTC
Getting warning while serving application and the application breaks.

```
WARNING in ./node_modules/ng-inline-svg/lib_esmodule/svg-cache.service.js 95:38-59
"export 'ɵɵdefineInjectable' (imported as 'i0') was not found in '@angular/core'

WARNING in ./node_modules/ng-inline-svg/lib_esmodule/inline-svg.service.js 54:39-60
"export 'ɵɵdefineInjectable' (imported as 'i0') was not found in '@angular/core'

WARNING in ./node_modules/ng-inline-svg/lib_esmodule/svg-cache.service.js 95:135-146
"export 'ɵɵinject' (imported as 'i0') was not found in '@angular/core'

WARNING in ./node_modules/ng-inline-svg/lib_esmodule/svg-cache.service.js 95:169-180
"export 'ɵɵinject' (imported as 'i0') was not found in '@angular/core'

WARNING in ./node_modules/ng-inline-svg/lib_esmodule/svg-cache.service.js 95:206-217
"export 'ɵɵinject' (imported as 'i0') was not found in '@angular/core'

WARNING in ./node_modules/ng-inline-svg/lib_esmodule/svg-cache.service.js 95:242-253
"export 'ɵɵinject' (imported as 'i0') was not found in '@angular/core'

WARNING in ./node_modules/ng-inline-svg/lib_esmodule/svg-cache.service.js 95:270-281
"export 'ɵɵinject' (imported as 'i0') was not found in '@angular/core'

WARNING in ./node_modules/ng-inline-svg/lib_esmodule/inline-svg.service.js 54:138-149
"export 'ɵɵinject' (imported as 'i0') was not found in '@angular/core'
```

**Temporary Fix:** 
Removing ee before **defineInjectable** and **inject** fixing the issue  
 `./node_modules/ng-inline-svg/lib_esmodule/inline-svg.service.js - line - 54`
`./node_modules/ng-inline-svg/lib_esmodule/svg-cache.service.js - line - 95`

## Version Used: 
ng-inline-svg : 8.3.0
Angular version : 7.2.7

**Comment by arkon** [comment] 2020-02-27 12:10
Duplicate of #125. You'll need to either update or use an older version.

**Closed as completed by arkon** 2020-02-27 12:10 UTC
