### ISSUE TITLE
replace contents inserts 2x

### ISSUE THREAD

**Issue by seanmcoleman** [arkon/ng-inline-svg#25] opened 2017-04-04 05:33 UTC
When `replaceContents` is `true`, the SVG element is inserted twice. 

If `replaceContents` is `true` and `prepend` is `false` (or omitted), then the SVG element replaces the content, but then an additional element is inserted. 

The culprit is here: https://github.com/arkon/ng-inline-svg/blob/master/src/inline-svg.directive.ts#L151

**Comment by seanmcoleman** [comment] 2017-04-04 05:39
@courdek

**Comment by arkon** [comment] 2017-04-04 17:32
@seanmcoleman Actually, I'm not seeing this. It seems to work fine in the demo.

**Comment by seanmcoleman** [comment] 2017-04-04 19:36
@arkon I'm not able to determine what parameters are used on the demo but if you look at the function I referenced, the bug is clear. If `replaceContents` is `true` and `prepend` is `false` (https://github.com/arkon/ng-inline-svg/blob/master/src/inline-svg.directive.ts#L152), the element contents are replaced by the SVG as expected. 

Subsequently, the line at https://github.com/arkon/ng-inline-svg/blob/master/src/inline-svg.directive.ts#L158 will always execute and append an additional element. 

I believe the fix is as simple as changing https://github.com/arkon/ng-inline-svg/blob/master/src/inline-svg.directive.ts#L156 to use `else if`.

**Comment by arkon** [comment] 2017-04-04 19:42
@seanmcoleman As noted in the README, `prepend` takes precedence over `replaceContents` (i.e. if it's true, the DOM element's contents are never cleared, which makes sense given [L152](https://github.com/arkon/ng-inline-svg/blob/master/src/inline-svg.directive.ts#L152).

The logic in `_insertEl` says:
```
if (replaceContents is true and prepend is false):
  clear contents

if (prepend is true):
  insert SVG at beginning of children
else:
  insert SVG at end of children
```

I don't see any reason why 2 SVGs might be inserted, unless the SVG is reinserted but the clearing function fails.

For reference, [here's the demo code](https://github.com/arkon/ng-inline-svg/blob/master/demo/src/demo/demo.component.ts).

**Comment by seanmcoleman** [comment] 2017-04-04 19:51
@arkon Thanks for the pseudocode. I think I misread the line where contents are cleared and thought it additionally inserted an element. 

I know this is lacking full context, but the following code generates 2 of the same SVG elements in this `span` while replacing the text `WORD`.
```
<span [inlineSVG]="'#increase-ring'" [replaceContents]=true>WORD</span>
```

The cause must be something else. My workaround is to restructure the HTML, but there is definitely a bug somewhere. Perhaps it's a touchpoint with Angular 4.0.0?

**Comment by arkon** [comment] 2017-04-04 20:03
@seanmcoleman The demo uses 4.0.x (since the newest version of ng-inline-svg relies on it anyway). What does that DOM node contain two `<use>` tags inside the inserted `<svg>`, or is it two `<svg>` tags?

**Comment by courdek** [comment] 2017-04-05 21:33
@arkon the node contains two `<svg>` tags which suggests to me that inlineSVG is executing twice somehow.

**Comment by arkon** [comment] 2017-04-19 14:46
This issue is still a mystery to me. Do the inputs ever change or something? Does this happen for every instance of the directive (if there's more than one)?

**Comment by maxkonoplin** [comment] 2017-07-12 11:03
I know what the problem is, it was as follows: svg files have the same id for the layers and when rendering inlineSvg it takes the first elements with the given id.

I`ve attached the files with which I had a problems.

[wizard.zip](https://github.com/arkon/ng-inline-svg/files/1141756/wizard.zip)

**Comment by maxkonoplin** [comment] 2017-07-12 11:03
[wizard.zip](https://github.com/arkon/ng-inline-svg/files/1141755/wizard.zip)

**Comment by arkon** [comment] 2017-07-12 11:06
@maxkonoplin Thanks for the SVGs! Which ID were you using with the directive, `path0_fill`?

**Comment by maxkonoplin** [comment] 2017-07-12 12:59
Yes!
I solved the problem by changing the id in svg files!

**Comment by arkon** [comment] 2017-07-12 16:05
@maxkonoplin So if I understand you correctly, if you used `path0_fill`, it would show both of the duplicate ID SVGs?

**Comment by arkon** [comment] 2017-07-12 23:41
I'm still only seeing a single SVG. :\

<img width="1680" alt="screen shot 2017-07-12 at 19 40 53" src="https://user-images.githubusercontent.com/4098258/28144546-0c38fee6-673a-11e7-806a-abd65f425466.png">

**Comment by maxkonoplin** [comment] 2017-07-13 13:03
Insert both svg which I sent into your component. When you load several images with repeated id, next images will render first image.

**Comment by arkon** [comment] 2017-07-13 15:28
@maxkonoplin I'm not sure I understand what you mean. Do you have an example of the template code?

**Comment by maxkonoplin** [comment] 2017-07-14 09:52
https://monosnap.com/file/YJbniH2JhPfLe7dUtN0dwzcHBfifj4
https://monosnap.com/file/td57s9c0QXvPw1J8KoAnIyMPX1ps6s

[return.zip](https://github.com/arkon/ng-inline-svg/files/1148013/return.zip)

**Comment by maxkonoplin** [comment] 2017-07-14 10:05
when i change id of path into svg files, this resolved this problems

**Comment by smarcov** [comment] 2017-07-14 10:08
I also reproduced with auto-generated svg ^_^

**Comment by arkon** [comment] 2017-07-14 16:42
Aaah I see the problem now. I guess this is inherent of having multiple SVGs inlined with conflicting IDs...

I'm against automatically ensuring that IDs are unique though. There's an option of wrapping the SVG in an `object` or something but I'm not sure that's much better.

That said, the proper solution is actually just to make sure your IDs aren't duplicated. 😛

**Comment by arkon** [comment] 2017-07-14 16:43
That said, I don't think the issue of ID conflicts has anything to do with the original issue. :(

**Comment by arkon** [comment] 2017-12-26 16:58
Closing this since I have yet to see this happen. Somebody can reopen it if they do see it.

**Closed as completed by arkon** 2017-12-26 16:58 UTC
Labels: bug
