### ISSUE TITLE
caching does not work - svg is taken from httpClient each time

### ISSUE THREAD

**Issue by kmolerov** [arkon/ng-inline-svg#84] opened 2018-07-05 09:08 UTC
sVGCacheService._cache is empty. 
I have *ngFor with repeated inline svg element. For each svg element http request is triggered.
I have debugged the code and found that even though this._cache.set(absUrl, svgEl); is called after http request, the next check in cache does not find any entries in it - cache is empty and that triggers the request again. 

This is a big issue, as it makes the application unusable as it kills the Ui when showing many repeated svgs.

**Comment by arkon** [comment] 2018-07-05 16:43
Duplicate of #83

**Closed as completed by arkon** 2018-07-05 16:43 UTC
