### ISSUE TITLE
Uncaught TypeError: i0.ɵɵdefineInjectable is not a function

### ISSUE THREAD

**Issue by praveen-angular** [arkon/ng-inline-svg#128] opened 2020-01-10 09:26 UTC
We are facing issue with ng-inline-svg:8.3.0 version, could not able to launch application.

**Comment by WilliamJWilson** [comment] 2020-01-10 10:26
Had same issue with ng-inline-svg:8.6.1.  Looks like an issue in the build pipeline where it's pulling a version of angular/core > 8.  Fixed it by altering package-lock.json to the following: -

    "ng-inline-svg": {
      "version": "8.6.0",
      "resolved": "https://registry.npmjs.org/ng-inline-svg/-/ng-inline-svg-8.6.0.tgz",
      "integrity": "sha512-DkJ9C7OXRbMzaqztckubrDMrH8tshU+wcs7PYpa+PUF3VewX/fxxUU36UHettDhWmeQhYyb6VL3T/ZuMBTbkCA=="
    }

Or go to package.json and limit the version for this package to no more than 8.6.0?

**Comment by arkon** [comment] 2020-01-11 19:38
Duplicate of #125

**Closed as completed by arkon** 2020-01-11 19:38 UTC
